### ISSUE TITLE
Integrate About.yml for ATF eRegs on 18F Dashboard

### ISSUE THREAD

**Issue by Journerdism** [18F/atf-eregs#167] opened 2015-12-08 18:08 UTC
Dashboard Update (From Greg Boone)
A small team from the Agile Guild is working on the Dashboard right now

A few months ago the Dashboard started pulling all project data from the Team API

We are working closely with the Team API and About.yml teams to get project data prepared for the Dashboard

If your project has an about.yml file in the main repo, that is where Dashboard’s data comes from

If your project doesn’t have an about.yml file, we look for a file in the data-private repo

We also keep a whitelist of projects in the Dashboard repo to filter out GitHub repos that are in the team API that don’t directly relate to a product or are components of products 

if your product is not on this list get in touch with Greg or drop in the #dashboard channel to get it added

We are currently working on finding ways to better integrate “child repos” and understand how 18F product teams describe their products so that we can better represent the work 18F is doing to the public

**Comment by cmc333333** [comment] 2015-12-08 18:09
See https://github.com/18F/about_yml

**Comment by cmc333333** [comment] 2016-02-17 23:14
Closing as a dupe of #370

**Closed by cmc333333** 2016-02-17 23:14 UTC
Labels: help wanted
